//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bes.Models.BesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceTable
    {
        public int invoiceID { get; set; }
        public int store_id { get; set; }
        public int bank_id { get; set; }
        public int expence_id { get; set; }
        public Nullable<decimal> cash { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string expenceDescription { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public Nullable<int> user_id { get; set; }
        public int odemeTuruTablosu_id { get; set; }
        public Nullable<byte> taksitSayisi { get; set; }
    
        public virtual bankTable bankTable { get; set; }
        public virtual expenceTable expenceTable { get; set; }
        public virtual odemeTuruTablosu odemeTuruTablosu { get; set; }
        public virtual storeTable storeTable { get; set; }
        public virtual userTable userTable { get; set; }
    }
}
