//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bes.Models.BesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class resfundTable
    {
        public int refundID { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> resfundType { get; set; }
        public string resfundDescription { get; set; }
        public string resfundFiles { get; set; }
        public Nullable<decimal> resfundCash { get; set; }
        public Nullable<System.DateTime> resfundDate { get; set; }
        public Nullable<decimal> resfundCredit { get; set; }
    
        public virtual bankTable bankTable { get; set; }
        public virtual resfundTypeTable resfundTypeTable { get; set; }
        public virtual storeTable storeTable { get; set; }
        public virtual userTable userTable { get; set; }
    }
}
