//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bes.Models.BesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTable()
        {
            this.FileTables = new HashSet<FileTables>();
            this.invoiceTable = new HashSet<invoiceTable>();
            this.resfundTable = new HashSet<resfundTable>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public Nullable<System.DateTime> loginDate { get; set; }
        public Nullable<System.DateTime> logoutDate { get; set; }
        public string user_position { get; set; }
        public string cashier_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTables> FileTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoiceTable> invoiceTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resfundTable> resfundTable { get; set; }
        public virtual roleTable roleTable { get; set; }
        public virtual storeTable storeTable { get; set; }
    }
}
