//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bes.Models.BesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvoiceLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Admin { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> newstore_id { get; set; }
        public Nullable<int> expence_id { get; set; }
        public Nullable<int> newexpence_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> newbank_id { get; set; }
        public Nullable<decimal> cash { get; set; }
        public Nullable<decimal> newcash { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> newcredit { get; set; }
        public decimal amount { get; set; }
        public decimal newamount { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public System.DateTime newinvoiceDate { get; set; }
        public string newexpenceCode { get; set; }
        public string expenceCode { get; set; }
        public string storeCode { get; set; }
        public string newstoreCode { get; set; }
        public string newbankCode { get; set; }
        public string bankCode { get; set; }
    }
}
